name: test_ml
channels:
  - conda-forge
dependencies:
  - python=3.9.2
  - scikit-learn=0.24.1
  - notebook=6.3.0
  - rise=5.7.1
  - pandas=1.2.3
  - matplotlib=3.3.4
  - flask-restful=0.3.8
  - pytest=6.2.2
  - requests=2.25.1
